[2024-12-13T11:38:56.895+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: odbc_test_dag.run_odbc_query manual__2024-12-13T11:38:48.918563+00:00 [queued]>
[2024-12-13T11:38:56.915+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: odbc_test_dag.run_odbc_query manual__2024-12-13T11:38:48.918563+00:00 [queued]>
[2024-12-13T11:38:56.916+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2024-12-13T11:38:56.949+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): run_odbc_query> on 2024-12-13 11:38:48.918563+00:00
[2024-12-13T11:38:56.957+0000] {standard_task_runner.py:57} INFO - Started process 504 to run task
[2024-12-13T11:38:56.962+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'odbc_test_dag', 'run_odbc_query', 'manual__2024-12-13T11:38:48.918563+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/test.py', '--cfg-path', '/tmp/tmpkymn74fl']
[2024-12-13T11:38:56.994+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask run_odbc_query
[2024-12-13T11:38:57.121+0000] {task_command.py:410} INFO - Running <TaskInstance: odbc_test_dag.run_odbc_query manual__2024-12-13T11:38:48.918563+00:00 [running]> on host 0a95521dabe4
[2024-12-13T11:38:57.453+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='odbc_test_dag' AIRFLOW_CTX_TASK_ID='run_odbc_query' AIRFLOW_CTX_EXECUTION_DATE='2024-12-13T11:38:48.918563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-13T11:38:48.918563+00:00'
[2024-12-13T11:39:27.586+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test.py", line 12, in execute_odbc_query
    conn = pyodbc.connect(conn_str)
pyodbc.OperationalError: ('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)')
[2024-12-13T11:39:27.607+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=odbc_test_dag, task_id=run_odbc_query, execution_date=20241213T113848, start_date=20241213T113856, end_date=20241213T113927
[2024-12-13T11:39:27.630+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 3 for task run_odbc_query (('HYT00', '[HYT00] [Microsoft][ODBC Driver 17 for SQL Server]Login timeout expired (0) (SQLDriverConnect)'); 504)
[2024-12-13T11:39:27.651+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-12-13T11:39:27.667+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
